%YAML 1.2
---
drivers:
  - /Volumes/VIPER_1TB
  - /Volumes/2_VIPER_1TB
  - /Volumes/WD01
  - /Volumes/WD02
  - /Volumes/WD03
  - /Volumes/WD04
  - /Volumes/WD05
unit: GB # options: KB, MB, GB, TB, PB, EB, ZB, JB
csv: 
    mode: daily
    dir: /Users/kk/drvcheck
    header:
      - MountedOn
      - Filesystem
      - Capacity
      - Size
      - Used
      - Avail
      - Time
      - MemUnit

...