%YAML 1.2
---
drivers: # mounted point or device
  #- /Volumes/Example1
  #- /Volumes/Example2
  
  - /Volumes/VIPER_1TB
  - /Volumes/WD01
  - /Volumes/WD02
  - /Volumes/WD03
  - /Volumes/WD04
  - /Volumes/WD05
unit: GB # options: KB, MB, GB, TB, PB, EB, ZB, JB
csv: 
    mode: daily
    dir: . # full path of csv storing directory, dot means current executable directory
    header:
      - MountedOn
      - Filesystem
      - Capacity
      - Size
      - Used
      - Avail
      - Time
      - MemUnit

...